server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    enabled: false
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/training_epam
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  cloud:
    discovery:
      enabled: false

logging:
  config: classpath:log-config/log4j2-dev.xml

resilience4j.ratelimiter:
  instances:
    authLimit:
      limit-for-period: 1000
      limit-refresh-period: 1s
      timeout-duration: 0