server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/training_epam
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  activemq:
    broker-url: tcp://activemq:61616
    user: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://eurekauser:eurekapassword@discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  config: classpath:log-config/log4j2-dev.xml